### ISSUE TITLE
request to cease publication

### ISSUE THREAD

**Issue by AckieSound** [Kawaxte/vs-medicine-rs#3]
Please remove this repository immediately. As the developer of VocalShifter, I am warning you. This is an unreasonable violation of my rights. If you do not remove it, I may take legal action.

**Comment by Kawaxte** [comment]
I am not taking infringement on your property, as the code I have written belongs to me.

There is no rule/law that forbids people to write open-source software that is done for educational purposes to learn for one's own enjoyment. I am not providing readily any binary forms, and this is not infringing on your copyright.

If you would like to discuss this further, instead of vaguely threatening me publicly, consider bringing this up in private.
